// Name: Pilot2 Ontology mapping
// This query returns a mapping object used by other import scripts
WITH {
  `RADIACION SOLAR`: 'RADIACION_SOLAR',
  `EDIFICIO ARFRISOL`: 'EDIFICIO_ARFRISOL_PV',
  `PARKING ARFRISOL`: 'PARKING_ARFRISOL_PV',
  `PEPA III`: 'PEPA_III',
  `PEPA III INVERSOR 1`: 'PEPA_III_INV1_PV',
  `PEPA III INVERSOR 2`: 'PEPA_III_INV2_PV',
  `PEPA III SEGUIDOR 3`: 'PEPA_III_TRACKER3_PV',
  `PEPA III SEGUIDOR 5`: 'PEPA_III_TRACKER5_PV',
  `PEPA III SEGUIDOR 6.1`: 'PEPA_III_TRACKER6_1_PV',
  `PEPA III SEGUIDOR 6.2`: 'PEPA_III_TRACKER6_2_PV',
  `PEPA III SEGUIDOR 7`: 'PEPA_III_TRACKER7_PV',
  `PEPA III SEGUIDOR 8`: 'PEPA_III_TRACKER8_PV',
  `PEPA III INVERSOR 9`: 'PEPA_III_INV9_PV',
  `PEPA III MICROINVERSORES`: 'PEPA_III_MICROINV_PV',

  `TURBINA`: 'TURBINA_Production',
  `CENTRAL TERMICA`: 'CENTRAL_THERMAL',

  `ED02`: 'ED02',
  `ED03`: 'ED03',
  `ED09`: 'ED09',

  `LECA 1`: 'LECA_1',
  `LECA 2`: 'LECA_2',

  `PEPA II`: 'PEPA_II',
  `PEPA_I`: 'PEPA_I',

  `RIOS`: 'RIOS',
  `ATLANTIC`: 'ATLANTIC',

  `VIENTO PEPA I`: 'VIENTO_PEPA_I',
  `VIENTO ESTACION`: 'VIENTO_ESTACION',

  `ENNERA 3.5`: 'ENNERA_3_5_Production',
  `WINDERA 4.2`: 'WINDERA_4_2_Production',

  `DEPOSITO NIVEL`: 'DEPOSITO_NIVEL',
  `DEPOSITO NIVEL LEVI`: 'DEPOSITO_NIVEL_LEVI',
  `DEPOSITO NIVEL INFERIOR`: 'DEPOSITO_NIVEL_INFERIOR',

  `BOMBAS`: 'BOMBAS',

  `BATERIA PEPA I`: 'BATERIA_PEPA_I_CARGA',
  `BATERIA PEPA II`: 'BATERIA_PEPA_II_CARGA',
  `BATERIA LITIO`: 'BATERIA_LITIO_CARGA',
  `BATERIA NMC PEPA II`: 'BATERIA_NMC_PEPA_II',
  `BATERIA REDOX`: 'BATERIA_REDOX',

  `GRUPO DIESEL`: 'GRUPO_DIESEL_Power',

  `ARFRISOL`: 'ARFRISOL_GENERIC',
  `LEVI`: 'LEVI',

  `VATIMETRO PEPA_III`: 'VATIMETRO_PEPA_III',
  `ACTARIS`: 'ACTARIS_Measurement'
} AS mapping
RETURN mapping;
